config/routes.rb
SleepingBeauty::Application.routes.draw do

  resources :heart_rates, :only => [:index, :create]

  resources :light_power, :only => [:index, :create] do
    get "last" => "light_power#last", :on => :collection
  end

  resources :rough_movements, :only => [:index, :create] do
    get "last_time" => "rough_movements#last_time", :on => :collection
  end

  delete "reset_system" => "application#reset_system", :as => :reset_system

  root :to => redirect('/light_power')

end

app/models/heart_rate.rb
class HeartRate < ActiveRecord::Base
  attr_accessible :rate, :time
end

app/models/light_power.rb
#    light_power.rb
# Purpose: Mid term demo
# Author: Matheus Camargo
#         matheus@go.wustl.edu
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 26, 2013
#
# Description
#   Model of MVC architecture for the light power data
#
class LightPower < ActiveRecord::Base
  attr_accessible :on, :time

  validates :on, :inclusion => { :in => [true, false] }
  validates :time, :presence => true

end

app/models/rough_movement.rb
#    rough_movement.rb
# Purpose: Mid term demo
# Author: Matheus Camargo
#         matheus@go.wustl.edu
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 26, 2013
#
# Description
#   Model of MVC architecture for the rough movement data
# Version Log
#   3/27/2013, Matheus Camargo
#      Added x, y, z to calculate the linear accelaration in the plot
#
class RoughMovement < ActiveRecord::Base
  attr_accessible :really_rough, :time, :x, :y, :z

  validates :really_rough, :inclusion => { :in => [true, false] }
  validates :time, :presence => true
  validates :x, :presence => true
  validates :y, :presence => true
  validates :z, :presence => true

end

app/controllers/application_controller.rb
#    application_controller.rb
# Purpose: Mid term demo
# Author: generated by rails
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 23, 2013
#
# Description
#    Base class for controllers
#
class ApplicationController < ActionController::Base
  protect_from_forgery

  def reset_system
  	RoughMovement.destroy_all
  	HeartRate.destroy_all
  	LightPower.destroy_all

  	redirect_to root_path
  end

end

app/controllers/heart_rates_controller.rb
#    heart_rates_controller.rb
# Purpose: Mid term demo
# Author: Matheus Camargo
#         matheus@go.wustl.edu
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 26, 2013
#
# Description
#    Controller of MVC architecture for the heart rate monitor in the Arduino
#
class HeartRatesController < ApplicationController

  # create
  # url post /heart_rates
  # This method creates a heart rate from post of format 
  # heart_rate[rate]; heart_rate[time]
  def create
    @heart_rate = HeartRate.new(params[:heart_rate])

    respond_to do |format|
      if @heart_rate.save
        # format.html
        format.xml { render :xml => @heart_rate, :status => :created, :location => @heart_rate }
      else
        # format.html
        format.xml { render :xml => @heart_rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # index
  # url get /heart_rates
  # Params: (optional) start_time
  # Returns all heart rates, after start_time if given
  def index
    if params[:start_time]
      @heart_rates = HeartRate.where("time >= ?", params[:start_time].to_f).order("time")
    else
      @heart_rates = HeartRate.order("time")
    end

    @heart_rates = @heart_rates.each_slice([@heart_rates.size, 2000].max/2000).map(&:first)

    respond_to do |format|
      format.html
      format.xml { render :xml => @heart_rates }
      format.json { render :json => @heart_rates }
    end
  end

end

app/controllers/light_power_controller.rb
#   light_power_controller.rb
# Purpose: Mid term demo
# Author: Matheus Camargo
#         matheus@go.wustl.edu
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 26, 2013
#
# Description
#    Controller of MVC architecture for the Light Power control
#
class LightPowerController < ApplicationController

  # create
  # url post /light_power
  # This method adds a change light power registry
  # Params: light_power (0 or 1) indicating if the light should be on or off
  def create
    @light_power = LightPower.new(params[:light_power])

    respond_to do |format|
      if @light_power.save
        # format.html
        format.xml { render :xml => @light_power, :status => :created, :location => @light_power }
      else
        # format.html
        format.xml { render :xml => @light_power.errors, :status => :unprocessable_entity }
      end
    end
  end

  # index
  # url get /light_power.xml
  # Params: (optional) start_time
  # Returns all accel_data, after start_time if given
  def index
    if params[:start_time]
      @light_powers = LightPower.where("time >= ?", params[:start_time].to_f)
    else
      @light_powers = LightPower.all
    end

    respond_to do |format|
      format.html
      format.xml { render :xml => @light_powers }
    end
  end

  # last
  # url get /light_power/last.txt
  # Returns the current light status (last registry)
  def last
    @last_status = LightPower.last

    respond_to do |format|
      if @last_status
        format.text { render :text => (@last_status.on ? "1," : "0,") + @last_status.time.to_i.to_s }
        format.json { render :json => @last_status, :only => :on }
      else
        format.text { render :text => "0,0" }
        format.json { render :json => { "on" => false } }
      end
    end
  end

end

app/controllers/rough_movements_controller.rb
#    rough_movements_controller.rb
# Purpose: Mid term demo
# Author: Matheus Camargo
#         matheus@go.wustl.edu
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 26, 2013
#
# Description
#    Controller of MVC architecture for the rough movements in the accelerometer
# Version Log
#    3/27/2013, Matheus Camargo
#       I added the json option for the rough movements
#
class RoughMovementsController < ApplicationController

  # create
  # url post /rough_movements
  # This method creates a set Rough movements from post of format 
  # rough_mov[i][roughy]; rough_mov[i][time]
  def create
    params[:rough_movs].each do |id, parameters|
      RoughMovement.create(parameters)
    end

    render :nothing => true
  end

  # index
  # url get /rough_movements.xml
  # Params: (optional) start_time
  # Returns all accel_data, after start_time if given
  def index
    if params[:start_time]
      @rough_movs = RoughMovement.where("time >= ?", params[:start_time].to_f).order("time")
    else
      @rough_movs = RoughMovement.order("time")
    end

    @rough_movs = @rough_movs.each_slice([@rough_movs.size, 2000].max/2000).map(&:first)

    respond_to do |format|
      format.html
      format.xml { render :xml => @rough_movs }
      format.json { render :content_type => 'application/json' }
    end
  end

  # last_time
  # url get /rough_movements/last_time.txt
  # Params: (optional) really_rough
  # Returns the last rough movement. If really_rough = 1, returns the last really rough movement
  def last_time
    if params[:really_rough] and params[:really_rough] == "1"
      @rough_mov = RoughMovement.where("really_rough = ?", true).last
    else
      @rough_mov = RoughMovement.last
    end

    respond_to do |format|
      if @rough_mov
        # format.html
        format.text { render :text => @rough_mov.time.to_i }
      else
        # format.html
        format.text { render :text => "-1" }
      end
    end
  end

end

app/helpers/application_helper.rb
#    application_helper.rb
# Purpose: Mid term demo
# Author: generated by rails
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 23, 2013
#
# Description
#    Helper for the whole application
#
module ApplicationHelper
end

app/helpers/heart_rates_helper.rb
module HeartRatesHelper
end

app/helpers/light_power_helper.rb
#    light_power_helper.rb
# Purpose: Mid term demo
# Author: generated by rails
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 26, 2013
#
# Description
#    Helper for light power
#
module LightPowerHelper
end

app/helpers/rough_movements_helper.rb
#    rough_movement_helper.rb
# Purpose: Mid term demo
# Author: generated by rails
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 26, 2013
#
# Description
#    Helper for rough movement
#
module RoughMovementsHelper
end

app/views/heart_rates/index.html.erb
<%# index.html.erb 
 Purpose: Mid term demo
 Author: Matheus Camargo
 		 matheus@go.wustl.edu
 CSE 467S -- Embedded Computing Systems
 WUSTL, Spring 2013
 Date: Mar., 25, 2013

 Description:
 	View of MVC architecture for accelerometer rough movements index
 	It shows the accelerometer graph based on the rough movements
%>

<%= javascript_include_tag "application", "jquery", "jquery.flot", "jquery.flot.selection" %>

<div id="chart"></div>
<div id="overview"></div>

<style>
	#nav {
		position:fixed;
		left:10px;
		top:14px;
		font: 15px Helvetica, Arial, sans-serif;
		z-index: 850;
	}
	#nav .info {
		width:30px;
		height:30px;
		position:absolute;
		top:0;
		left:0;
		cursor: pointer;
		background-image: url('<%= asset_path 'images/info.png' %>');
	}
	#nav a {
		color: rgb(85, 85, 85);
		text-decoration: none;
	}
	#nav a:hover {
		color: black;
	}
	#nav .menu {
		white-space: nowrap;
		position:absolute;
		margin-left: 40px;
		top:0px;
		display: none;
	}
	#nav .links {
		margin-left:4px;
		border: 1px solid rgb(190, 190, 190);
		background-color: #F6F6F6;
		box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2);
		border-radius: 3px 3px 3px 3px;
		z-index: 810;
	}
	#nav .links ul {
		margin: 0px;
		padding: 0px;
		list-style: none;
	}
	#nav .links ul li {
		border-bottom: 1px solid white;
	}
	#nav .links ul li:last-child {
		border-bottom: none;
		border-radius: 0px 0px 3px 3px;
	}
	#nav .links ul li:first-child {
		border-radius: 3px 3px 0px 0px;
	}
	#nav .links ul li a {
		padding: 9px 11px;
		display: block;
	}
	#nav .links ul li:hover {
		background-color: #F2F2F2;
	}
	#nav .arrow {
		background-image: url('<%= asset_path 'images/arrow.gif' %>');
		height:8px;
		width:5px;
		position:absolute;
		z-index:910;
		top:12px;
		left: 0px;
	}
	#invisible {
		margin:0;
		padding: 0;
		width:100%;
		height:100%;
		position: absolute;
		top:0;
		left:0;
		display:none;
		z-index:710;
	}
</style>
<div id="nav">
	<a class="info"></a>
	<div class="menu">
		<div class="links">
			<ul>
				<li><%= link_to "Heart Rates Graph", heart_rates_path %></li>
				<li><%= link_to "Rough Movements Graph", rough_movements_path %></li>
				<li><%= link_to "Light Power Status", light_power_index_path %></li>
				<li><%= link_to 'Reset System', reset_system_path, :method => :delete, :data => { confirm: 'Are you sure?' } %></li>
			</ul>
		</div>
		<span class="arrow"></span>
	</div>
</div>
<div id="invisible"></div>
<script>
	$(".info").bind("click", function() {
		$(".menu").toggle();
		$("#invisible").toggle();			
	});
	$("#invisible").bind("click", function() {
		$(".menu").hide();
		$("#invisible").hide();
	});
</script>

<script type="text/javascript">
	$(function () {

		$("#chart").height(500).width($(window).width() - 200).css("margin", "40px auto 20px");
		$("#overview").height(100).width($(window).width() - 100).css("margin", "20px auto 20px");

		var plot, overview;

		var plot_options = {
			xaxis: { mode: "time" },
    		selection: { mode: "x" }
		};
		var overview_options = {
			series: {
				lines: { show: true, lineWidth: 1 },
				shadowSize: 0
			},
			xaxis: { mode: "time" },
			yaxis: { ticks: [], autoscaleMargin: 0.1 },
			selection: { mode: "x" },
			legend: { show: false }
		};

		var data = [
			{
				"label": "rate",
				"data": <%= @heart_rates.map{ |rv| [rv.time, rv.rate] } %>
			}
		];

		plot = $.plot($("#chart"), data, plot_options);
		overview =  $.plot($("#overview"), data, overview_options);

		$("#chart").bind("plotselected", function (event, ranges) {
			// do the zooming
			plot = $.plot($("#chart"), data,
				$.extend(true, {}, plot_options, {
					xaxis: { min: ranges.xaxis.from, max: ranges.xaxis.to }
			}));
			// don't fire event on the overview to prevent eternal loop
			overview.setSelection(ranges, true);
		});
    
		$("#overview").bind("plotselected", function (event, ranges) {
			plot.setSelection(ranges);
		});

	});
</script>

app/views/layouts/application.html.erb
<%# application.html.erb 
 Purpose: Mid term demo
 Author: Matheus Camargo
 		 matheus@go.wustl.edu
 CSE 467S -- Embedded Computing Systems
 WUSTL, Spring 2013
 Date: Mar., 23, 2013

 Description:
 	Defines default HTML structure
%>
<!DOCTYPE html>
<html>
<head>
  <title>SleepingBeauty</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/light_power/index.html.erb
<%# index.html.erb 
 Purpose: Mid term demo
 Author: Matheus Camargo
 		 matheus@go.wustl.edu
 CSE 467S -- Embedded Computing Systems
 WUSTL, Spring 2013
 Date: Mar., 25, 2013

 Description:
 	View of MVC architecture for light power index
%>
<%= javascript_include_tag "application", "jquery" %>

<style>
	body {
		background-color: black;
	}
	#light {
		width: 600px;
		height: 600px;
		margin: 30px auto 0;
	}
	.on {
		background-position: center;
		background-repeat: no-repeat;
		background-image: url('<%= asset_path 'images/light_on.jpg' %>');
	}
	.off {
		background-position: center;
		background-repeat: no-repeat;
		background-image: url('<%= asset_path 'images/light_off.jpg' %>');
	}
</style>

<div id="light">
</div>

<style>
	#nav {
		position:fixed;
		left:10px;
		top:14px;
		font: 15px Helvetica, Arial, sans-serif;
		z-index: 850;
	}
	#nav .info {
		width:30px;
		height:30px;
		position:absolute;
		top:0;
		left:0;
		cursor: pointer;
		background-image: url('<%= asset_path 'images/info.png' %>');
	}
	#nav a {
		color: rgb(85, 85, 85);
		text-decoration: none;
	}
	#nav a:hover {
		color: black;
	}
	#nav .menu {
		white-space: nowrap;
		position:absolute;
		margin-left: 40px;
		top:0px;
		display: none;
	}
	#nav .links {
		margin-left:4px;
		border: 1px solid rgb(190, 190, 190);
		background-color: #F6F6F6;
		box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2);
		border-radius: 3px 3px 3px 3px;
		z-index: 810;
	}
	#nav .links ul {
		margin: 0px;
		padding: 0px;
		list-style: none;
	}
	#nav .links ul li {
		border-bottom: 1px solid white;
	}
	#nav .links ul li:last-child {
		border-bottom: none;
		border-radius: 0px 0px 3px 3px;
	}
	#nav .links ul li:first-child {
		border-radius: 3px 3px 0px 0px;
	}
	#nav .links ul li a {
		padding: 9px 11px;
		display: block;
	}
	#nav .links ul li:hover {
		background-color: #F2F2F2;
	}
	#nav .arrow {
		background-image: url('<%= asset_path 'images/arrow.gif' %>');
		height:8px;
		width:5px;
		position:absolute;
		z-index:910;
		top:12px;
		left: 0px;
	}
	#invisible {
		margin:0;
		padding: 0;
		width:100%;
		height:100%;
		position: absolute;
		top:0;
		left:0;
		display:none;
		z-index:710;
	}
</style>
<div id="nav">
	<a class="info"></a>
	<div class="menu">
		<div class="links">
			<ul>
				<li><%= link_to "Heart Rates Graph", heart_rates_path %></li>
				<li><%= link_to "Rough Movements Graph", rough_movements_path %></li>
				<li><%= link_to "Light Power Status", light_power_index_path %></li>
				<li><%= link_to 'Reset System', reset_system_path, :method => :delete, :data => { confirm: 'Are you sure?' } %></li>
			</ul>
		</div>
		<span class="arrow"></span>
	</div>
</div>
<div id="invisible"></div>
<script>
	$(".info").bind("click", function() {
		$(".menu").toggle();
		$("#invisible").toggle();			
	});
	$("#invisible").bind("click", function() {
		$(".menu").hide();
		$("#invisible").hide();
	});
</script>

<script type="text/javascript">

	function update_light() {
	    $.ajax({
	        url: "<%= last_light_power_index_url :format => :json %>",
	        success: function (last_light_power) {
	        	if(last_light_power.on) {
	        		$("#light").addClass("on").removeClass("off");
	        	} else {
	        		$("#light").addClass("off").removeClass("on");
	        	}
	        	setTimeout(update_light, 200);
	        }
	    });
	}

	$(function () {
		update_light();
	});

</script>

app/views/rough_movements/index.html.erb
<%# index.html.erb 
 Purpose: Mid term demo
 Author: Matheus Camargo
 		 matheus@go.wustl.edu
 CSE 467S -- Embedded Computing Systems
 WUSTL, Spring 2013
 Date: Mar., 25, 2013

 Description:
 	View of MVC architecture for accelerometer rough movements index
 	It shows the accelerometer graph based on the rough movements
%>

<%= javascript_include_tag "application", "jquery", "jquery.flot", "jquery.flot.selection" %>

<div id="chart"></div>
<div id="overview"></div>

<style>
	#nav {
		position:fixed;
		left:10px;
		top:14px;
		font: 15px Helvetica, Arial, sans-serif;
		z-index: 850;
	}
	#nav .info {
		width:30px;
		height:30px;
		position:absolute;
		top:0;
		left:0;
		cursor: pointer;
		background-image: url('<%= asset_path 'images/info.png' %>');
	}
	#nav a {
		color: rgb(85, 85, 85);
		text-decoration: none;
	}
	#nav a:hover {
		color: black;
	}
	#nav .menu {
		white-space: nowrap;
		position:absolute;
		margin-left: 40px;
		top:0px;
		display: none;
	}
	#nav .links {
		margin-left:4px;
		border: 1px solid rgb(190, 190, 190);
		background-color: #F6F6F6;
		box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2);
		border-radius: 3px 3px 3px 3px;
		z-index: 810;
	}
	#nav .links ul {
		margin: 0px;
		padding: 0px;
		list-style: none;
	}
	#nav .links ul li {
		border-bottom: 1px solid white;
	}
	#nav .links ul li:last-child {
		border-bottom: none;
		border-radius: 0px 0px 3px 3px;
	}
	#nav .links ul li:first-child {
		border-radius: 3px 3px 0px 0px;
	}
	#nav .links ul li a {
		padding: 9px 11px;
		display: block;
	}
	#nav .links ul li:hover {
		background-color: #F2F2F2;
	}
	#nav .arrow {
		background-image: url('<%= asset_path 'images/arrow.gif' %>');
		height:8px;
		width:5px;
		position:absolute;
		z-index:910;
		top:12px;
		left: 0px;
	}
	#invisible {
		margin:0;
		padding: 0;
		width:100%;
		height:100%;
		position: absolute;
		top:0;
		left:0;
		display:none;
		z-index:710;
	}
</style>
<div id="nav">
	<a class="info"></a>
	<div class="menu">
		<div class="links">
			<ul>
				<li><%= link_to "Heart Rates Graph", heart_rates_path %></li>
				<li><%= link_to "Rough Movements Graph", rough_movements_path %></li>
				<li><%= link_to "Light Power Status", light_power_index_path %></li>
				<li><%= link_to 'Reset System', reset_system_path, :method => :delete, :data => { confirm: 'Are you sure?' } %></li>
			</ul>
		</div>
		<span class="arrow"></span>
	</div>
</div>
<div id="invisible"></div>
<script>
	$(".info").bind("click", function() {
		$(".menu").toggle();
		$("#invisible").toggle();			
	});
	$("#invisible").bind("click", function() {
		$(".menu").hide();
		$("#invisible").hide();
	});
</script>

<script type="text/javascript">
	$(function () {

		$("#chart").height(500).width($(window).width() - 200).css("margin", "40px auto 20px");
		$("#overview").height(100).width($(window).width() - 100).css("margin", "20px auto 20px");

		var plot, overview;

		var plot_options = {
			xaxis: { mode: "time" },
    		selection: { mode: "x" }
		};
		var overview_options = {
			series: {
				lines: { show: true, lineWidth: 1 },
				shadowSize: 0
			},
			xaxis: { mode: "time" },
			yaxis: { ticks: [], autoscaleMargin: 0.1 },
			selection: { mode: "x" },
			legend: { show: false }
		};

		var data = [
			{
				"label": "x",
				"data": <%= @rough_movs.map{ |rv| [rv.time, rv.x] } %>
			},
			{
				"label": "y",
				"data": <%= @rough_movs.map{ |rv| [rv.time, rv.y] } %>
			},
			{
				"label": "z",
				"data": <%= @rough_movs.map{ |rv| [rv.time, rv.z] } %>
			}
		];

		plot = $.plot($("#chart"), data, plot_options);
		overview =  $.plot($("#overview"), data, overview_options);

		$("#chart").bind("plotselected", function (event, ranges) {
			// do the zooming
			plot = $.plot($("#chart"), data,
				$.extend(true, {}, plot_options, {
					xaxis: { min: ranges.xaxis.from, max: ranges.xaxis.to }
			}));
			// don't fire event on the overview to prevent eternal loop
			overview.setSelection(ranges, true);
		});
    
		$("#overview").bind("plotselected", function (event, ranges) {
			plot.setSelection(ranges);
		});

	});
</script>

app/views/rough_movements/index.json.erb
[
	{
		"label": "x",
		"data": <%= @rough_movs.map{ |rv| [rv.time, rv.x] } %>
	},
	{
		"label": "y",
		"data": <%= @rough_movs.map{ |rv| [rv.time, rv.y] } %>
	},
	{
		"label": "z",
		"data": <%= @rough_movs.map{ |rv| [rv.time, rv.z] } %>
	}
]